spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:library
  jpa:
    hibernate:
      ddl-auto:

jwt:
  expiration-time: 172800000
  secret-key: 07yu3SFdFVPYck4VLy5lXpAKSHyZF4rgTUbGd2_yhHA1BfCoc0HzUpLryfugxZilnkDNK9aFV
  token-prefix: Bearer