spring:
  profiles:
    active: ${PROFILE_ACTUAL:test}
  jackson:
    serialization:
      indent-output: true
  mail:
    username: teste
    password: teste
  freemarker:
    template-loader-path: classpath:/templates

server:
  servlet:
    context-path: /api