spring:
  profiles:
    active: ${PROFILE_ACTUAL:test}
  jackson:
    serialization:
      indent-output: true
  mail:
    username: teste
    password: teste
  freemarker:
    template-loader-path: classpath:/templates
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  servlet:
    context-path: /api
