spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    driver-class-name: org.postgresql.Driver

jwt:
  expiration-time: ${JWT_EXPIRATION_TIME}
  secret-key: ${JWT_SECRET_KEY}
  token-prefix: ${JWT_TOKEN_PREFIX}